language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3

addons:
  postgresql: "9.4"

services:
  - postgresql

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/907e95dada362be2a13c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
